name: Build & Push Airflow
on:
  push:
    branches: [ main ]
    paths:
      - 'infra/airflow/**'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/airflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # permite publicar no GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t $IMAGE_NAME:commit-${{ github.sha }} infra/airflow
          docker tag $IMAGE_NAME:commit-${{ github.sha }} $IMAGE_NAME:latest

      - name: Push
        run: |
          docker push $IMAGE_NAME:commit-${{ github.sha }}
          docker push $IMAGE_NAME:latest