name: Release
on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          draft: false